### ISSUE TITLE
overwrite=yes cause serious issues

### ISSUE THREAD

**Issue by mkraetke** [transpect/unzip-extension#2]
The step `tr:unzip` is suitable to delete files unintentionally when the option `overwrite=yes` is set.
- unzip removes the entire directory recursively instead of overwriting particular files in the directory
- the step throws no exceptions when invalid paths are passed as options, e.g. strings which include only a forward slash
- the step raise an error when it attempts to unzip files in the directory where the zip file is stored (`$ unzip -o  myarchve.zip -d .`)

**Comment by gimsieke** [comment]
The overwrite option shouldn’t be implemented as a recursive delete, followed by unzip. It should create/re-use/chmod folders as needed but never delete folders.

**Comment by gimsieke** [comment]
See https://github.com/transpect/unzip-extension/issues/7#issuecomment-248215232 for a solution proposal, balancing the competing requirements of avoiding inadvertant catastrophic deletions and determining a correct representation of an archive’s contents (a thing that the entries list apparently does not provide, thus calling for recursive deletion followed by a recursive directory listing).

**Comment by mkraetke** [comment]
> The overwrite option shouldn’t be implemented as a recursive delete, followed by unzip

Is this still an requirement? I think we discussed that we keep the recursive delete because we do not want to have obsolete files from earlier unzips.
On the other hand it's now permitted to overwrite your root directory. We can also think of adding a blacklist with _protected_ system directories such as `/etc`, `c:/windows` etc.

**Comment by mkraetke** [comment]
ok, we keep the recursive delete but do not allow to use this together with the root directory of the file system.
