### ISSUE TITLE
unzipping does not work stable.

### ISSUE THREAD

**Issue by BrackXs** [transpect/unzip-extension#5]
In folgendem Paket erhalte ich beim Auspacken den Fehler ERROR: no-file:no-file

[Validerung2.zip](https://github.com/transpect/unzip-extension/files/302020/Validerung2.zip)

Unzip mittels Windows-Explorer oder Linux unzip funktioniert problemlos.

**Comment by lwittmar** [comment]
There is an invalid Local File Header at the beginning of this zip-File:
00000000  50 4b 30 30 50 4b 03 04  14 00 02 00 08 00 17 5a  |PK00PK.........Z|

Winzip and linux unzip seem to ignore/fix this error.
Zipinfo notices the problem:
Central directory entry 1:
001_d.tif
offset of local header from start of archive:   4
...
Central directory entry  2:
There are an extra -36 bytes preceding this file.

zip -FFv input.zip --out output.zip fixes these kinds of problems

**Comment by BrackXs** [comment]
OK. But what to do about it? It is hard to communicate that the problem is caused by a faulty zip-file if it is usable using both windows and linux unzip.

**Comment by mkraetke** [comment]
I rewrote the unzip extension in d1a802f1e40859de6f638e223d02ea447b9f4033 and replaced `java.util.zip.ZipInputStream` with `java.util.zip.ZipFile`. Besides some other improvements, this solved your issue, too.
