### ISSUE TITLE
"An empty sequence is not allowed as the value of variable $base-uri"

### ISSUE THREAD

**Issue by ptkw** [transpect/unzip-extension#6]
I am trying to run `docx2hub` as described in the **Getting started** section of the transpect website.

However, any attempts to execute it via `calabash` yield the following error:
`$ ./calabash/calabash.sh -o result=MyXMLfile.xml docx2hub/xpl/docx2hub.xpl docx=test.docx`
`ERROR: file:/C:/cygwin64/home/FOXRABBIT/test10/docx2hub/xpl/single-tree.xpl:err:XTTE0570:An empty sequence is not allowed as the value of variable $base-uri`
`ERROR: An empty sequence is not allowed as the value of variable $base-uri`
`ERROR:     cause: file:/C:/cygwin64/home/FOXRABBIT/test10/docx2hub/xpl/single-tree.xpl:err:XTTE0570:An empty sequence is not allowed as the value of variable $base-uri`
`ERROR: An empty sequence is not allowed as the value of variable $base-uri`
`ERROR:     cause: file:/C:/cygwin64/home/FOXRABBIT/test10/docx2hub/xpl/single-tree.xpl:err:XTTE0570:An empty sequence is not allowed as the value of variable $base-uri`
`ERROR: Pipeline failed: An empty sequence is not allowed as the value of variable $base-uri`
`ERROR: Underlying exception: An empty sequence is not allowed as the value of variable $base-uri`

I tracked it down as an issue with the `unzip-extension` (`base-url` is a variable featured in the `zip-manifest` portion of the `docx2hub`'s `single-tree.xpl`) Substituting the current version of the `unzip-extension` folder with the one taken from the `docx2tex` package seems to solve the problem.

**Comment by gimsieke** [comment]
This is due to https://github.com/transpect/unzip-extension/issues/1#issuecomment-245586707.
But even after this will have been fixed, we’d still need to insert an additional step that flattens the new unzip output structure. 
For the time being, I’d recommend to stick with the fixed submodule revisions that you’ll get when you do

```
git clone https://github.com/transpect/docx2jats-demo --recursive
```

**Comment by ptkw** [comment]
Many thanks for suggesting the `docx2jats-demo` - a "stable release" like this might come in handy when learning the framework.

**Comment by mkraetke** [comment]
The URI is now constructed with `new File(pathString).getCanonicalFile().toURI()`. If it's not possible to construct a valid URI, an error is thrown.
